# Generated by Django 5.0.4 on 2024-04-22 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtiflowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('atiflowmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atiflow.atiflowmodel')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            bases=('atiflow.atiflowmodel',),
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('atiflowmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atiflow.atiflowmodel')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('url_repositorio', models.URLField()),
                ('url_test', models.URLField()),
                ('url_produccion', models.URLField()),
                ('url_documentacion', models.URLField()),
            ],
            bases=('atiflow.atiflowmodel',),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('atiflowmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atiflow.atiflowmodel')),
                ('detalle', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('atiflow.atiflowmodel',),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('atiflowmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atiflow.atiflowmodel')),
                ('titulo', models.CharField(max_length=100)),
                ('comentarios', models.ManyToManyField(to='atiflow.comentario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atiflow.estadotarea')),
            ],
            bases=('atiflow.atiflowmodel',),
        ),
    ]
