# Generated by Django 5.0.4 on 2024-04-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='url_documentacion',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='url_produccion',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='url_repositorio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='url_test',
            field=models.URLField(blank=True, null=True),
        ),
    ]
