# Generated by Django 5.0.4 on 2024-04-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0002_alter_sistema_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('atiflowmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atiflow.atiflowmodel')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('LE', 'Lenguaje'), ('FR', 'Framework'), ('LI', 'Librería'), ('BD', 'Base de Datos'), ('OT', 'Otro')], default='OT', max_length=2)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('atiflow.atiflowmodel',),
        ),
    ]
