# Generated by Django 5.0.4 on 2024-04-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0005_sistema_tipo_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='tipo_soporte',
            field=models.CharField(choices=[('AT', 'ATI-DCC'), ('SI', 'Sistemas'), ('DE', 'Desconocido')], default='DE', max_length=2),
        ),
    ]
