# Generated by Django 5.0.4 on 2024-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0007_sistema_sistema_padre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='sistema_padre',
        ),
        migrations.AddField(
            model_name='sistema',
            name='dependencias',
            field=models.ManyToManyField(blank=True, to='atiflow.sistema'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, default=None, to='atiflow.tecnologia'),
        ),
    ]
