# Generated by Django 5.0.4 on 2024-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0008_remove_sistema_sistema_padre_sistema_dependencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='tipo_ambiente',
        ),
        migrations.AlterField(
            model_name='sistema',
            name='tipo_autenticacion',
            field=models.CharField(choices=[('SA', 'Sin Autenticación'), ('PR', 'Propia'), ('UC', 'Portal Ucampus'), ('UP', 'U-Pasaporte'), ('OT', 'Otra')], default='SA', max_length=2),
        ),
    ]
