# Generated by Django 5.0.4 on 2024-04-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0009_remove_sistema_tipo_ambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='tipo_autenticacion',
            field=models.CharField(choices=[('SA', 'Sin Autenticación'), ('PR', 'Propia'), ('UC', 'Portal Ucampus'), ('UP', 'U-Pasaporte'), ('SU', 'SAU'), ('OT', 'Otra')], default='SA', max_length=2),
        ),
    ]
