# Generated by Django 5.0.4 on 2024-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0010_alter_sistema_tipo_autenticacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='managed',
            field=models.BooleanField(default=False),
        ),
    ]
