# Generated by Django 5.0.4 on 2024-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0011_sistema_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='tiene_api',
            field=models.BooleanField(default=False),
        ),
    ]
