# Generated by Django 5.0.4 on 2024-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0012_sistema_tiene_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='detalle',
            field=models.TextField(),
        ),
    ]
