# Generated by Django 5.0.4 on 2024-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0013_alter_comentario_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
