# Generated by Django 5.0.4 on 2024-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0015_rename_detalle_comentario_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='atiflow.comentario'),
        ),
    ]
