# Generated by Django 5.0.4 on 2024-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0016_alter_tarea_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('NI', 'No Iniciada'), ('PR', 'En Progreso'), ('TE', 'Terminada'), ('CA', 'Cancelada')], default='NI', max_length=2),
        ),
        migrations.DeleteModel(
            name='EstadoTarea',
        ),
    ]
