# Generated by Django 5.0.4 on 2024-04-23 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0018_tarea_sistemas_afectados'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('NI', 'No Iniciada'), ('ES', 'En Espera'), ('PR', 'En Progreso'), ('TE', 'Terminada'), ('CA', 'Cancelada')], default='NI', max_length=2),
        ),
    ]
