# Generated by Django 5.0.4 on 2024-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atiflow', '0019_tarea_fecha_solicitud_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_solicitud',
            field=models.DateField(),
        ),
    ]
